import type { SettingKey } from '../db/repositories';
import type { CheckoutField } from '../services/checkoutFields';
import type { AdminOrderAction } from '../services/orderStatus';

/**
 * Every callback_data string the bot emits, in one place. Handlers match the same shapes with regexes.
 * Short "ns:verb:id" strings keep well under Telegram's 64-byte limit.
 */
export const CB = {
  noop: 'noop',
  home: 'home',
  shop: 'shop',
  category: (id: number) => `cat:${id}`,
  product: (id: number) => `prod:${id}`,
  qty: (id: number, qty: number) => `qty:${id}:${qty}`,
  add: (id: number, qty: number) => `add:${id}:${qty}`,
  cart: 'cart',
  clearCart: 'cart:clear',
  removeItem: (itemId: number) => `cart:del:${itemId}`,
  checkout: 'checkout',
  /** At the checkout name step: use the name from the customer's Telegram profile. */
  useTelegramName: 'co:tgname',
  /** Checkout, scheduled category: choose a day / a time / go back to the days. */
  slotDay: (categoryId: number, day: number) => `sd:${categoryId}:${day}`,
  slotPick: (categoryId: number, at: number) => `sl:${categoryId}:${at}`,
  slotDays: (categoryId: number) => `sb:${categoryId}`,
  /** Gives up the checkout in progress (and the times it holds). */
  cancelCheckout: 'co:cancel',
  myOrders: 'orders',
  faqs: 'faqs',
  faq: (id: number) => `faq:${id}`,
  help: 'help',
  support: 'support',

  admin: {
    root: 'a:root',
    stats: 'a:stats',
    cancel: 'a:cancel',
    settings: 'a:settings',
    admins: 'a:admins',
    removeAdmin: (chatId: number) => `a:admins:rm:${chatId}`,
    editSetting: (key: SettingKey) => `a:set:${key}`,
    schedule: 'a:sch',
    scheduleToggle: 'a:sch:toggle',
    scheduleCategory: (id: number) => `a:sch:cat:${id}`,
    schedulePreset: (id: number, key: string) => `a:sch:preset:${id}:${key}`,
    scheduleDays: (id: number) => `a:sch:days:${id}`,
    scheduleDay: (id: number, weekday: number) => `a:sch:day:${id}:${weekday}`,
    scheduleDaySet: (id: number, mask: number) => `a:sch:dayset:${id}:${mask}`,
    scheduleTimes: (id: number) => `a:sch:times:${id}`,
    scheduleLabel: (id: number) => `a:sch:label:${id}`,
    scheduleChoices: (id: number, what: 'cap' | 'lead' | 'hor') => `a:sch:pick:${id}:${what}`,
    scheduleSet: (id: number, what: 'cap' | 'lead' | 'hor', value: number) => `a:sch:set:${id}:${what}:${value}`,
    scheduleEnable: (id: number) => `a:sch:en:${id}`,
    scheduleDelete: (id: number) => `a:sch:del:${id}`,
    scheduleDeleteConfirm: (id: number) => `a:sch:delok:${id}`,
    closedDays: 'a:sch:closed',
    closedDay: (day: number) => `a:sch:closed:${day}`,
    agenda: 'a:agenda',
    agendaDay: (day: number) => `a:agenda:${day}`,
    checkoutFields: 'a:cof',
    toggleCheckoutField: (field: CheckoutField) => `a:cof:${field}`,
    faqs: 'a:faqs',
    addFaq: 'a:faq:add',
    faq: (id: number) => `a:faq:${id}`,
    editFaq: (id: number, field: 'question' | 'answer') => `a:faq:edit:${id}:${field}`,
    toggleFaq: (id: number) => `a:faq:toggle:${id}`,
    deleteFaq: (id: number) => `a:faq:del:${id}`,
    deleteFaqConfirm: (id: number) => `a:faq:delok:${id}`,
    categories: 'a:cats',
    addCategory: 'a:cat:add',
    category: (id: number) => `a:cat:${id}`,
    editCategory: (id: number, field: 'name' | 'icon') => `a:cat:edit:${id}:${field}`,
    toggleCategory: (id: number) => `a:cat:toggle:${id}`,
    deleteCategory: (id: number) => `a:cat:del:${id}`,
    deleteCategoryConfirm: (id: number) => `a:cat:delok:${id}`,
    products: 'a:prods',
    productsPage: (page: number) => `a:prods:${page}`,
    addProduct: 'a:prod:add',
    product: (id: number) => `a:prod:${id}`,
    editProduct: (id: number) => `a:prod:edit:${id}`,
    editField: (id: number, field: string) => `a:prod:field:${id}:${field}`,
    pickCategory: (id: number) => `a:prod:cat:${id}`,
    setCategory: (id: number, catId: number) => `a:prod:setcat:${id}:${catId}`,
    toggleProduct: (id: number) => `a:prod:toggle:${id}`,
    newProductCategory: (catId: number) => `a:prod:newcat:${catId}`,
    orders: 'a:orders',
    ordersPage: (page: number) => `a:orders:${page}`,
    customers: 'a:users',
    customersPage: (page: number) => `a:users:${page}`,
    findCustomer: 'a:users:find',
    customer: (userId: number, ordersPage = 0) => (ordersPage ? `a:user:${userId}:${ordersPage}` : `a:user:${userId}`),
    toggleCustomerBlock: (userId: number) => `a:user:block:${userId}`,
    messageCustomer: (userId: number) => `a:user:msg:${userId}`,
    order: (id: number) => `a:order:${id}`,
    orderAction: (id: number, action: AdminOrderAction) => `a:order:${action}:${id}`,
    contactBuyer: (orderId: number) => `a:dialog:${orderId}`,
    closeDialog: (buyerChatId: number) => `a:dialog:close:${buyerChatId}`,
  },
} as const;
